version: '3.8'

services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    ports:
      - "8080:8080"
    volumes:
      - ./customFiles:/customFiles:rw
      - ./configs:/configs:rw
      - ./logs:/logs:rw
      - ./tessdata:/usr/share/tessdata:rw
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - SECURITY_ENABLELOGIN=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
    restart: unless-stopped
